name: Java CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install virtual display for JavaFX (headless)
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Build with Maven (headless JavaFX)
        run: xvfb-run --auto-servernum mvn -B clean package --file pom.xml

      - name: Run unit tests
        run: xvfb-run --auto-servernum mvn test
