name: Maven Build and Deploy Javadoc

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Publish Javadoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: target/site/apidocs   # ✅ includes ALL files (HTML + CSS + resources)
          clean: true